apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: flask-mongo-ns
type: Opaque
data:
  username: bW9uZ291c2Vy     # base64 of 'mongouser'
  password: cGFzc3dvcmQxMjM= # base64 of 'password123'
